name: Test Sourcemod compilation

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"

      - name: Compile plugins
        run: |
          mkdir "/plugins/"
          spcomp -w234 -O2 -v2 -o"/plugins/classwars.smx" /scripting/classwars.sp
          echo "===OUT FILES==="
          ls "/plugins"
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}